version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  co2monitor:
    build: .
    container_name: co2monitor
    device:
    - /dev/hidraw0 
    ports:
    - 8888:8888
    command:
    - --no-decrypt-message
    - /dev/hidraw0
  grafana:
    image: grafana/grafana-oss:8.2.0
    ports:
      - 3000:3000
    volumes:
      - other/grafana/datasources:/etc/grafana/provisioning/datasources      